[package]
name = "gen_graph"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "gen_graph"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
layout-rs = "0.1.1"
rustler = "0.29.1"
