[package]
name = "gen_graph"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "gen_graph"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
graphviz-rust = "0.6.6"
rustler = "0.29.1"
